name: ci pipeline
on: [push]

jobs:
  test:
    name: Rspec tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.2'
          bundler-cache: true

      - name: Step 3 - Run RSpec Tests
        run: bundle exec rspec

  lint:
    name: Rubocop linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.2'

      - name: Install dependencies
        run: bundle install

      - name: Run Rubocop
        run: bundle exec rubocop

  audit:
    name: Bundle Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.2'

      - name: Install dependencies
        run: bundle install

      - name: Run audit
        run: bundle audit