name: ci pipeline
on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout Code
        uses: actions/checkout@v4

      - name: Step 2 - Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.2'

      - name: Step 3. Install dependencies
        run: bundle install

      - name: Step 4 -Run RSpec Tests
        run: bundle exec rspec
